"""Order execution adapters.

Paper first. The live adapter is an interface only, and there is a hard gate in
front of it: `LiveExecutionAdapter.submit` must refuse unless a human has
confirmed the specific order. That is not configurable, because the whole point
of a confirmation gate is that it cannot be turned off by the code that wants to
trade.

The paper adapter deliberately reuses the SAME fill model as the backtester. If
paper fills were generated by different code from backtest fills, agreement
between the two would prove nothing.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime

from ..core.types import Bar, Fill, InstrumentSpec, Order
from ..backtest.costs import CostModel, VolatilityScaledCostModel
from ..backtest.fills import FillModel, NextBarOpenFill


class ExecutionError(RuntimeError):
    pass


class ConfirmationRequired(ExecutionError):
    """Raised when a real-money order is submitted without human sign-off."""


class ExecutionAdapter(ABC):
    """Interface for placing orders."""

    @property
    @abstractmethod
    def is_live(self) -> bool:
        ...

    @abstractmethod
    def submit(self, order: Order, **context: object) -> Fill | None:
        ...


@dataclass
class PaperExecutionAdapter(ExecutionAdapter):
    """Simulated execution using the backtest fill machinery.

    Requires the bar the order will execute in, so it cannot fill at the signal
    price - the same constraint the engine operates under.
    """

    instrument: InstrumentSpec
    cost_model: CostModel = field(default_factory=VolatilityScaledCostModel)
    fill_model: FillModel = field(default_factory=NextBarOpenFill)
    fills: list[Fill] = field(default_factory=list)

    @property
    def is_live(self) -> bool:
        return False

    def submit(
        self,
        order: Order,
        execution_bar: Bar | None = None,
        bar_volatility: float = 0.0,
        **context: object,
    ) -> Fill | None:
        if execution_bar is None:
            raise ExecutionError(
                "paper execution needs the bar the order will fill in. Filling at "
                "the signal price is the bug this system exists to prevent."
            )
        fill = self.fill_model.fill(
            order, execution_bar, self.instrument, self.cost_model, bar_volatility
        )
        if fill is not None:
            self.fills.append(fill)
        return fill


class LiveExecutionAdapter(ExecutionAdapter):
    """Base for real-money adapters (Robinhood Agentic Trading, broker of choice).

    Unimplemented on purpose. Before any subclass sends a real order, the
    strategy must have:

      1. a PASS verdict from the walk-forward + cost-sensitivity report,
      2. a paper track record of at least the sample size you specify,
      3. a human sign-off on this specific order.

    `confirm` implements (3) and has no bypass flag.
    """

    def __init__(self, confirmed_orders: set[str] | None = None) -> None:
        self._confirmed = confirmed_orders or set()

    @property
    def is_live(self) -> bool:
        return True

    @staticmethod
    def order_token(order: Order) -> str:
        """Stable identity for one specific order, for confirmation matching.

        Includes side, quantity, symbol and timestamp so a confirmation cannot be
        reused for a different order than the one a human actually looked at.
        """
        return f"{order.symbol}|{order.side.name}|{order.quantity:g}|{order.ts.isoformat()}"

    def confirm(self, order: Order) -> str:
        token = self.order_token(order)
        self._confirmed.add(token)
        return token

    def submit(self, order: Order, **context: object) -> Fill | None:
        token = self.order_token(order)
        if token not in self._confirmed:
            raise ConfirmationRequired(
                f"live order {token} has not been confirmed by a human. "
                "Call confirm(order) from an interactive session first."
            )
        self._confirmed.discard(token)  # one confirmation, one order
        return self._place(order, **context)

    @abstractmethod
    def _place(self, order: Order, **context: object) -> Fill | None:
        """Broker-specific placement. Implement in a subclass."""
